export const routes = {
  public: {
    home: "/",
    features: "/features",
    privacy: "/privacy",
    terms: "/terms",
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
  },
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    courses: "/admin/courses",
    courseCreate: "/admin/courses/new",
    courseEdit: "/admin/courses/course-id/edit",
    rooms: "/admin/rooms",
    roomCreate: "/admin/rooms/new",
    roomEdit: "/admin/rooms/room-id/edit",
    sessions: "/admin/sessions",
    sessionCreate: "/admin/sessions/new",
    sessionDetail: "/admin/sessions/session-id",
    sections: "/admin/sections",
    sectionCreate: "/admin/sections/new",
    sectionEdit: "/admin/sections/section-id/edit",
    users: "/admin/users",
    profile: "/admin/profile",
    usersNew: "/admin/users/new",
    userEdit: "/admin/users/membership-id/edit",
    studentImport: "/admin/students/import",
    reports: "/admin/reports",
    settings: "/admin/settings",
  },
  instructor: {
    root: "/instructor",
    dashboard: "/instructor/dashboard",
    sessions: "/instructor/sessions",
    sessionCreate: "/instructor/sessions/new",
    sessionDetail: "/instructor/sessions/session-id",
    reports: "/instructor/reports",
    profile: "/instructor/profile",
    students: "/instructor/students",
    studentCreate: "/instructor/students/new",
    studentImport: "/instructor/students/import",
  },
  student: {
    root: "/student",
    scan: "/student/scan",
    scanResult: "/student/scan/result",
    attendance: "/student/attendance",
    profile: "/student/profile",
  },
} as const;
