export const routes = {
  public: {
    home: "/",
    features: "/features",
    privacy: "/privacy",
    terms: "/terms",
    login: "/login",
    register: "/register",
  },
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    courses: "/admin/courses",
    courseCreate: "/admin/courses/new",
    sessions: "/admin/sessions",
    sessionCreate: "/admin/sessions/new",
    sessionDetail: "/admin/sessions/session-id",
    sections: "/admin/sections",
    sectionCreate: "/admin/sections/new",
    users: "/admin/users",
    usersNew: "/admin/users/new",
    reports: "/admin/reports",
    settings: "/admin/settings",
  },
  instructor: {
    root: "/instructor",
    dashboard: "/instructor/dashboard",
    sessions: "/instructor/sessions",
    sessionDetail: "/instructor/sessions/session-id",
    students: "/instructor/students",
    studentCreate: "/instructor/students/new",
  },
  student: {
    root: "/student",
    scan: "/student/scan",
    scanResult: "/student/scan/result",
    attendance: "/student/attendance",
    profile: "/student/profile",
  },
} as const;
