ALTER TYPE "PresenceCheckStatus" ADD VALUE IF NOT EXISTS 'LOW_ACCURACY';

ALTER TYPE "AttendanceAlertType" ADD VALUE IF NOT EXISTS 'OUTSIDE_GEOFENCE';
ALTER TYPE "AttendanceAlertType" ADD VALUE IF NOT EXISTS 'LOW_ACCURACY_LOCATION';
ALTER TYPE "AttendanceAlertType" ADD VALUE IF NOT EXISTS 'DUPLICATE_CHECK_IN_ATTEMPT';
ALTER TYPE "AttendanceAlertType" ADD VALUE IF NOT EXISTS 'EXPIRED_TOKEN_ATTEMPT';
ALTER TYPE "AttendanceAlertType" ADD VALUE IF NOT EXISTS 'REVOKED_TOKEN_ATTEMPT';
ALTER TYPE "AttendanceAlertType" ADD VALUE IF NOT EXISTS 'STUDENT_NOT_ENROLLED';
ALTER TYPE "AttendanceAlertType" ADD VALUE IF NOT EXISTS 'SESSION_CLOSED_ATTEMPT';
ALTER TYPE "AttendanceAlertType" ADD VALUE IF NOT EXISTS 'INVALID_TOKEN_ATTEMPT';
