import {
  BarChart3,
  CalendarDays,
  Download,
  FileBarChart,
  FileSpreadsheet,
  TrendingUp,
  Users,
} from "lucide-react";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { EmptyState } from "@/components/ui/EmptyState";
import { PageHeader } from "@/components/ui/PageHeader";
import { SectionCard } from "@/components/ui/SectionCard";
import { StatCard } from "@/components/ui/StatCard";
import { StatusBadge } from "@/components/ui/StatusBadge";

const summaryStats = [
  {
    label: "Attendance rate",
    value: "91%",
    trend: "Mock",
    description: "Aggregate placeholder across completed sessions.",
    icon: <TrendingUp className="h-4 w-4" aria-hidden="true" />,
    tone: "success" as const,
  },
  {
    label: "Sessions reported",
    value: "24",
    trend: "30 days",
    description: "Future count from completed session records.",
    icon: <CalendarDays className="h-4 w-4" aria-hidden="true" />,
    tone: "info" as const,
  },
  {
    label: "Participants",
    value: "128",
    trend: "Demo",
    description: "Placeholder enrolled participant coverage.",
    icon: <Users className="h-4 w-4" aria-hidden="true" />,
    tone: "neutral" as const,
  },
];

const reportCards = [
  {
    title: "Attendance summary",
    description: "Session-level present, late, absent, and excused totals.",
    status: "Ready for data",
    icon: <FileBarChart className="h-4 w-4" aria-hidden="true" />,
  },
  {
    title: "Participation trends",
    description: "Longitudinal participation by course, section, and cohort.",
    status: "Planned",
    icon: <BarChart3 className="h-4 w-4" aria-hidden="true" />,
  },
  {
    title: "Export package",
    description: "CSV-friendly records for academic or training operations.",
    status: "Planned",
    icon: <FileSpreadsheet className="h-4 w-4" aria-hidden="true" />,
  },
];

const trendBars = [72, 88, 64, 94, 81, 91, 78];

export default function AdminReportsPage() {
  return (
    <>
      <PageHeader
        eyebrow="Reporting"
        title="Reports"
        description="Analyze attendance outcomes and prepare export-ready summaries for operational teams."
      >
        <ButtonLink
          href="/admin/reports"
          variant="primary"
          icon={<Download className="h-4 w-4" aria-hidden="true" />}
        >
          Export CSV
        </ButtonLink>
      </PageHeader>

      <section className="grid gap-4 md:grid-cols-3">
        {summaryStats.map((stat) => (
          <StatCard key={stat.label} {...stat} />
        ))}
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        <SectionCard
          title="Attendance trend"
          description="Visual placeholder for future report aggregation."
        >
          <div className="flex min-h-64 items-end gap-3 rounded-lg border border-neutral-200 bg-neutral-50 px-4 py-5">
            {trendBars.map((height, index) => (
              <div key={index} className="flex flex-1 flex-col items-center gap-2">
                <div
                  className="w-full rounded-t-md bg-neutral-900"
                  style={{ height: `${height}%` }}
                />
                <span className="text-xs text-neutral-500">D{index + 1}</span>
              </div>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          title="Export queue"
          description="Reports generated by background jobs will be tracked here later."
        >
          <EmptyState
            title="No exports generated"
            description="CSV and PDF export jobs will appear here once report generation is connected."
            icon={<Download className="h-5 w-5" aria-hidden="true" />}
          />
        </SectionCard>
      </section>

      <SectionCard
        title="Report library"
        description="Reusable report surfaces prepared for future data sources."
      >
        <div className="grid gap-4 lg:grid-cols-3">
          {reportCards.map((report) => (
            <div
              key={report.title}
              className="rounded-lg border border-neutral-200 bg-neutral-50 p-4"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-md bg-white text-neutral-600 shadow-subtle">
                  {report.icon}
                </div>
                <StatusBadge
                  label={report.status}
                  tone={report.status === "Ready for data" ? "info" : "warning"}
                />
              </div>
              <h3 className="mt-4 font-semibold text-neutral-950">
                {report.title}
              </h3>
              <p className="mt-2 text-sm leading-6 text-neutral-600">
                {report.description}
              </p>
            </div>
          ))}
        </div>
      </SectionCard>

      <SectionCard
        title="Report filters"
        description="Date range, course, section, and role filters will control generated reports."
      >
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {["Date range", "Course", "Section", "Attendance status"].map(
            (filter) => (
              <div
                key={filter}
                className="rounded-md border border-neutral-200 bg-neutral-50 px-3 py-2"
              >
                <p className="text-xs font-medium uppercase tracking-normal text-neutral-500">
                  {filter}
                </p>
                <p className="mt-1 text-sm font-medium text-neutral-900">
                  All
                </p>
              </div>
            ),
          )}
        </div>
      </SectionCard>
    </>
  );
}
